accounts: {
  $SYS: {
    users: [
      { user: admin, password: password }
    ]
  },
  EDGE_1: {
    jetstream: enabled,
    users: [
      { user: edge1, password: password }
    ]
  },
  EDGE_2: {
    jetstream: enabled,
    users: [
      { user: edge2, password: password }
    ]
  }
}

jetstream {}

system_account: "$SYS"

cluster: {
  name: AP,
  port: 6222,
  routes: [
    "nats://ap_1:6222"
  ]
}

gateway: {
  name: AP,
  port: 7222,
  gateways: [
    { name: NA, url: "nats://na_1:7222" }
    { name: EU, url: "nats://eu_1:7222" }
    { name: AP, url: "nats://ap_1:7222" }
  ]
}

leafNodes {
  port: 7422
}